### ISSUE TITLE
使用netty4报如下错误，用netty3访问正常

### ISSUE THREAD

**Issue by ccvcd** [ofpay/dubbo-remoting-netty4#2]
打印调用过程，发现远程调用几次后，客户端发送了消息，服务器端没有收到消息，然后客户端报超时，使用官方netty可以正常调用

com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method grantServices in the service com.xxx.spruce.esb.service.AppAccountService. Tried 3 times of the providers [75.81.1.172:20880](1/1) from the registry 75.81.1.106:2181 on the consumer 75.81.1.172 using the dubbo version 2.5.4-SNAPSHOT. Last error is: Invoke remote method timeout. method: grantServices, provider: dubbo://75.81.1.172:20880/com.xxx.spruce.esb.service.AppAccountService?anyhost=true&application=bcs-demo-client&check=false&client=netty4&default.delay=-1&default.timeout=5000&delay=-1&dubbo=2.5.4-SNAPSHOT&generic=false&interface=com.xxx.spruce.esb.service.AppAccountService&methods=getAppAccountInfos,changeAppSecret,grantServices,getMqServices,getApiServices,delAppAccountInfo,getAppAccountInfo,getAppAccount,passAppAccountInfo,getAppCertEntity,saveAppAccountInfo&payload=168388608&pid=5376&serialization=dubbo&server=netty4&side=consumer&timestamp=1445917875667, cause: Waiting server-side response timeout. start time: 2015-10-27 11:51:27.403, end time: 2015-10-27 11:51:32.411, client elapsed: 0 ms, server elapsed: 5008 ms, timeout: 5000 ms, request: Request [id=14, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=grantServices, parameterTypes=[class com.xxx.spruce.esb.pojo.AppAccountInfo], arguments=[com.xxx.spruce.esb.pojo.AppAccountInfo@122fd03], attachments={path=com.xxx.spruce.esb.service.AppAccountService, interface=com.xxx.spruce.esb.service.AppAccountService, timeout=5000, version=0.0.0}]], channel: /75.81.1.172:51904 -> /75.81.1.172:20880
    at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:101)
    at com.alibaba.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:227)
    at com.alibaba.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:77)
    at com.alibaba.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:52)
    at com.alibaba.dubbo.common.bytecode.proxy0.grantServices(proxy0.java)
    at com.xxx.bcs.demo.consumer.DemoConsumer.main(DemoConsumer.java:72)
Caused by: com.alibaba.dubbo.remoting.TimeoutException: Waiting server-side response timeout. start time: 2015-10-27 11:51:27.403, end time: 2015-10-27 11:51:32.411, client elapsed: 0 ms, server elapsed: 5008 ms, timeout: 5000 ms, request: Request [id=14, version=2.0.0, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=grantServices, parameterTypes=[class com.xxx.spruce.esb.pojo.AppAccountInfo], arguments=[com.xxx.spruce.esb.pojo.AppAccountInfo@122fd03], attachments={path=com.xxx.spruce.esb.service.AppAccountService, interface=com.xxx.spruce.esb.service.AppAccountService, timeout=5000, version=0.0.0}]], channel: /75.81.1.172:51904 -> /75.81.1.172:20880
    at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:107)
    at com.alibaba.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:84)
    at com.alibaba.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:99)
    at com.alibaba.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:144)
    at com.alibaba.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:74)
    at com.alibaba.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:53)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
    at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
    at com.alibaba.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:48)
    at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:91)
    at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:53)
    at com.alibaba.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:77)
    ... 5 more

**Comment by ccvcd** [comment]
最终发现是服务端接收包的问题，后修改NettyCodecAdapter类InternalDecoder子类，应用正常调用。
    private class InternalDecoder extends ByteToMessageDecoder {
        private int    mOffset = 0, mLimit = 0;
        private byte[] mBuffer = null;

```
    @Override
    protected void decode(ChannelHandlerContext ctx, ByteBuf input, List<Object> out) throws Exception {
        int readable = input.readableBytes();
        if (readable <= 0) {
            return;
        }
        int off, limit;
        byte[] buf = mBuffer;
        if (buf == null) {
            buf = new byte[bufferSize];
            off = limit = 0;
        } else {
            off = mOffset;
            limit = mLimit;
        }
        NettyChannel channel = NettyChannel.getOrAddChannel(ctx.channel(), url, handler);
        boolean remaining = true;
        Object msg;
        UnsafeByteArrayInputStream bis;
        try {
            do {
                // read data into buffer.
                int read = Math.min(readable, buf.length - limit);
                input.readBytes(buf, limit, read);
                limit += read;
                readable -= read;
                bis = new UnsafeByteArrayInputStream(buf, off, limit - off);
                // decode object.
                do {
                    try {
                        ChannelBuffer bf = ChannelBuffers.wrappedBuffer(input2byte(bis));
                        msg = codec.decode(channel, bf);
                    } catch (IOException e) {
                        remaining = false;
                        throw e;
                    }                        
                    if (msg == Codec2.DecodeResult.NEED_MORE_INPUT) {
                        if (off == 0) {
                            if (readable > 0) {
                                buf = Bytes.copyOf(buf, buf.length << 1);
                            }
                        } else {
                            int len = limit - off;
                            System.arraycopy(buf, off, buf, 0, len); // adjust buffer.
                            off = 0;
                            limit = len;
                        }
                        break;
                    } else {
                        int pos = bis.position();
                        if (off == pos) {
                            remaining = false;
                            throw new IOException("Decode without read data.");
                        }
                        if (msg != null) {
                            out.add(msg);
                        }
                        off = pos;
                    }
                } while (bis.available() > 0);
            } while (readable > 0);
        } finally {
            if (remaining) {
                int len = limit - off;
                if (len < buf.length / 2) {
                    System.arraycopy(buf, off, buf, 0, len);
                    off = 0;
                    limit = len;
                }
                mBuffer = buf;
                mOffset = off;
                mLimit = limit;
            } else {
                mBuffer = null;
                mOffset = mLimit = 0;
            }
            NettyChannel.removeChannelIfDisconnected(ctx.channel());
        }
    }
}

private final byte[] input2byte(InputStream in)  throws IOException {  
    ByteArrayOutputStream out = new ByteArrayOutputStream();  
    byte[] b = new byte[bufferSize];
    int len;
    while ((len = in.read(b)) != -1) {
        out.write(b, 0, len);
    }
    out.flush();
    return out.toByteArray();  
}
```

**Comment by wuwen5** [comment]
移步官方
https://github.com/alibaba/dubbo/tree/master/dubbo-remoting/dubbo-remoting-netty4
